apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphic-web
spec:
  template:
    spec:
      containers:
      - name: morphic-web
        env:
          - name: SERVICE_URL
            value: "https://api.morphic-staging.com/"
          - name: RECAPTCHA_KEY
            value: "6Lc1hfsUAAAAAGFReCJUUva4LHF30XG5pIoJr2Nl"
          - name: MORPHIC_WINDOWS_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.0.20170.1.msi"
          - name: MORPHIC_WINDOWS_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.0.20170.1.appcast.xml"
