apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphic-web
spec:
  template:
    spec:
      containers:
      - name: morphic-web
        env:
          - name: SERVICE_URL
            value: "https://api.morphic.org/"
          - name: RECAPTCHA_KEY
            value: "6LcuEM0ZAAAAABafZkUPUBAAcj5BNw2rd3fuNMC2"
          - name: MORPHIC_WINDOWS_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/stable/MorphicSetup-v1.0.20260.1.msi"
          - name: MORPHIC_WINDOWS_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/stable/MorphicSetup-v1.0.20260.1.appcast.xml"
          - name: MORPHIC_MAC_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/stable/Morphic-v0.20260.8.dmg"
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: MORPHIC_COMMUNITY_REGISTRATION_URL
            value: "https://community.morphic.org/#/register"
