apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphic-web
spec:
  template:
    spec:
      containers:
      - name: morphic-web
        env:
          - name: SERVICE_URL
            value: "https://dev-morphic.morphiclite-oregondesignservices.org"
          - name: RECAPTCHA_KEY
            value: "6Le6hfsUAAAAAB9-WagMKxjnZmP7RKrSxlTYjJc-"