apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphic-web
spec:
  template:
    spec:
      containers:
      - name: morphic-web
        env:
          - name: SERVICE_URL
            value: "https://dev-morphic.morphiclite-oregondesignservices.org/"
          - name: RECAPTCHA_KEY
            value: "6Lc1hfsUAAAAAGFReCJUUva4LHF30XG5pIoJr2Nl"
          - name: MORPHIC_WINDOWS_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.0.20232.1.msi"
          - name: MORPHIC_WINDOWS_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.0.20232.1.appcast.xml"
          - name: MORPHIC_MAC_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/edge/Morphic-v0.20218.3.dmg"
          - name: MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/internal/MorphicCommunitySetup-v1.0.20240.2.msi"  # scaffold:download-url:MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL
